---
title: "Homework_W6D03"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(infer)
```

##Task 1
```{r}
ames <- read_csv("data/ames.csv") %>% clean_names()
```

##Task 2
```{r}
ames %>% 
  ggplot(aes(lot_area)) + 
  geom_histogram()
```
Has a huge outlier so the distribution is skewed to the right



##Task 3
```{r}
ames_bootstrap <- ames %>%
    specify(response = lot_area) %>%
    generate(reps = 10000, type = "bootstrap") %>%
    calculate(stat = "mean")

ames_bootstrap %>% 
  ggplot() + 
  geom_histogram(aes(stat))
```

##Task 4
```{r}
ames_bootstrap_95 <- ames_bootstrap %>% 
  get_ci(level = 0.95, type = "percentile")

ames_bootstrap %>% 
  visualise(bins = 30) + 
  shade_ci(endpoints = ames_bootstrap_95)
```

##Task 5
```{r}
ames_bootstrap_99 <- ames_bootstrap %>% 
  get_ci(level = 0.99, type = "percentile")

ames_bootstrap %>% 
  visualise(bins = 30) + 
  shade_ci(endpoints = ames_bootstrap_99)
```
It's alot broader than the 95% as it covers alot more values which don't get
captured inside the 95% graph in task4, so using 99 should give a more realistic
view of the standard `lot_areas` captured in the sample.

##Task 6
```{r}
point_mean <- ames_bootstrap %>% 
  summarise(mean = mean(stat))

point_mean

mean_ames_org_data <- ames %>% 
  summarise(mean = mean(lot_area))
mean_ames_org_data
```

#EXT
##Task 1
```{r}
ames_pre_1920 <- ames %>%
  mutate(before_1920 = as.numeric(year_built < 1920))
```

#rep 200
```{r}
bs_ames_200 <- ames_pre_1920 %>%
    specify(response = before_1920) %>%
    generate(reps = 200, type = "bootstrap") %>%
    calculate(stat = "mean") 

bs_ames_95_1 <- bs_ames_200 %>% 
  get_ci(level = 0.95, type = "percentile") 
bs_ames_95_1

bs_ames_200 %>% 
  visualise(bins = 30) + 
  shade_ci(endpoints = bs_ames_95_1)

ames_200_mean <- bs_ames_200 %>% 
  summarise(mean = mean(stat))

ames_200_mean
```

#rep 50000
```{r}
bs_ames_50k <- ames_pre_1920 %>%
    specify(response = before_1920) %>%
    generate(reps = 50000, type = "bootstrap") %>%
    calculate(stat = "mean") 

bs_ames_95_2 <- bs_ames_50k %>% 
  get_ci(level = 0.95, type = "percentile") 
bs_ames_95_2

bs_ames_50k %>% 
  visualise(bins = 30) + 
  shade_ci(endpoints = bs_ames_95_2)

ames_50k_mean <- bs_ames_50k %>% 
  summarise(mean = mean(stat))

ames_50k_mean
```

