---
title: "HOMEWORK"
output: html_notebook
---

```{r}
library(tidyverse)
library(CodeClanData)
```


#MVP
##Question 1.
```{r}
backpack_data <- backpack

glimpse(backpack_data)
```

##Question 2.

```{r}
ggplot(backpack_data) +
  aes(x = backpack_weight) +
  geom_histogram(bins = 20, col = "white") 
```

##Question 3.
```{r}
ggplot(backpack_data ,aes(x = backpack_weight, fill = sex)) +
  geom_bar() +
  facet_wrap(~ sex)
```


##Question 4.
```{r}
ggplot(backpack_data) +
  aes(
    x = body_weight,
    y = backpack_weight
  ) +
  geom_point() + 
  geom_smooth(method = "lm", se = FALSE) +
  labs(x = "body weight", y = "backpack weight")
```


## Question 5.
```{r}
  ggplot(backpack_data) +
  aes(x = body_weight, y = backpack_weight, colour = sex) +
  geom_point() +
  facet_wrap(~sex) +
  labs(x = "body weight", y = "backpack weight")
```


## Question 6.
```{r}
backpack_data <- backpack_data %>% 
  mutate(backpain_labelled = recode(back_problems, 
                       "0" = "No", 
                       "1" = "Yes"))

ggplot(backpack_data, aes(x = backpain_labelled)) +
  geom_bar()
```


## Question 7.
```{r}
ggplot(backpack_data) + 
  aes(x = backpain_labelled, fill = backpain_labelled) + 
  geom_bar() +
  labs(x = "backpain reported", y = "student count") + 
  facet_wrap(~sex)
```


## Question 8.
```{r}
#added labels
pain_labels <- c("backpain: no", "backpain: yes")
names(pain_labels) <- c("No", "Yes")
sex_labels <- c("sex: female", "sex: male")
names(sex_labels) <- c("Female", "Male")


ggplot(backpack_data,
       aes(x = body_weight, y = backpack_weight, colour = backpain_labelled)) +
  geom_point() +
  facet_grid(sex ~ backpain_labelled,
             labeller = labeller(backpain_labelled = pain_labels, sex = sex_labels))
```

